#!/usr/bin/env python3
"""
Update R2, R3, R4 questions with options from READING_SETS
"""

import os
import json
import urllib.request

env_path = '/Users/clintviegas/Desktop/React JS/CELPIP/.env'
env_vars = {}
with open(env_path, 'r') as f:
    for line in f:
        if '=' in line and not line.startswith('#'):
            key, value = line.strip().split('=', 1)
            env_vars[key] = value

supabase_url = env_vars.get('VITE_SUPABASE_URL')
anon_key = env_vars.get('VITE_SUPABASE_ANON_KEY')

headers = {
    'apikey': anon_key,
    'Content-Type': 'application/json',
    'Prefer': 'return=minimal'
}

# R2 data
r2_data = [
    {"number": 1, "options": ["A) Monday, April 7", "B) Tuesday, April 8", "C) Thursday, April 10", "D) Friday, April 11"]},
    {"number": 2, "options": ["A) One", "B) Two", "C) Three", "D) Four"]},
    {"number": 3, "options": ["A) The instructor is unavailable that day.", "B) The pool is closed for maintenance.", "C) Enrolment was too low to justify the class.", "D) A special event is taking place in the pool area."]},
    {"number": 4, "options": ["A) registration … online", "B) payment … in person", "C) confirmation … by phone", "D) booking … by email"]},
    {"number": 5, "options": ["A) He will find the pool class running as normal.", "B) He will find a Chair Yoga session in Room 2 instead.", "C) He will be told all Thursday classes are cancelled.", "D) He will be redirected to Tuesday's aquatic fitness class."]},
]

# R3 data
r3_data = [
    {"number": 1, "options": ["A) To argue that computers should not be used in schools.", "B) To identify the problem of insufficient digital literacy instruction and discuss efforts to address it.", "C) To praise British Columbia's education system.", "D) To explain why teachers reject professional development training."]},
    {"number": 2, "options": ["A) 32%", "B) 50%", "C) 68%", "D) Over 75%"]},
    {"number": 3, "options": ["A) It increases the cost of education per student.", "B) It creates gaps where students may learn some skills but miss critical others.", "C) Teachers are not willing to integrate digital literacy.", "D) Technology companies refuse to provide resources to schools."]},
    {"number": 4, "options": ["A) Visible", "B) Irregular or incomplete", "C) Contaminated", "D) Covered with patterns"]},
    {"number": 5, "options": ["A) To suggest that older teachers should retire immediately.", "B) To imply that teachers are resistant to change.", "C) To explain why teachers may lack the instinctive understanding of digital literacy that younger people have.", "D) To criticize teachers for not investing in their own education."]},
    {"number": 6, "options": ["A) Ontario and Quebec", "B) British Columbia and Ontario", "C) British Columbia and Alberta", "D) Alberta and Saskatchewan"]},
    {"number": 7, "options": ["A) Nobody needs to learn digital skills in university or at work.", "B) Universities and employers expect students and employees to already possess digital skills, rather than providing training.", "C) Teachers in universities are better at teaching digital skills than high school teachers.", "D) Digital skills are less important in university than in K–12 education."]},
    {"number": 8, "options": ["A) Enthusiastically optimistic about recent progress.", "B) Dismissive of efforts by teachers and school boards.", "C) Concerned about gaps but hopeful about emerging solutions.", "D) Angry and accusatory toward provincial governments."]},
    {"number": 9, "options": ["A) Schools can choose to invest in these areas or not, depending on budget.", "B) Investment should be voluntary and left to individual teachers.", "C) These investments are essential and necessary if schools want to serve their students well.", "D) The government should restrict schools from spending on digital literacy."]},
]

# R4 data
r4_data = [
    {"number": 1, "options": ["A) Dr. Catherine Liu", "B) James Chen", "C) Both speakers agree on this point", "D) Neither speaker addresses this issue"]},
    {"number": 2, "options": ["A) It is impossible to solve", "B) It is a teaching and assessment problem, not a technology problem", "C) Schools should ban AI to prevent plagiarism", "D) Teachers cannot adapt to AI tools"]},
    {"number": 3, "options": ["A) Students cannot use them correctly", "B) Teachers cannot supervise their use", "C) AI companies profit from user data and content generated by students", "D) AI is too expensive for schools"]},
    {"number": 4, "options": ["A) Mathematics textbooks", "B) Wikipedia", "C) Scientific journals", "D) Government policy documents"]},
    {"number": 5, "options": ["A) Marketing or promotion", "B) Close and careful examination", "C) Restriction or limitation", "D) Investment or funding"]},
    {"number": 6, "options": ["A) Dr. Liu acknowledges bias exists; Chen denies it", "B) Dr. Liu wants regulation to address bias; Chen suggests teaching students to critically evaluate AI output", "C) Chen believes bias is solved through transparency; Dr. Liu does not", "D) Chen supports all AI use; Dr. Liu opposes all AI use"]},
    {"number": 7, "options": ["A) To suggest that all technology should be banned", "B) To argue that data privacy is not important", "C) To show that the problem (data harvesting) is separate from the solution (education)", "D) To prove that electricity is more important than AI"]},
    {"number": 8, "options": ["A) Pessimistic and defeatist", "B) Reflective and philosophical", "C) Angry and accusatory", "D) Sarcastic and dismissive"]},
    {"number": 9, "options": ["A) AI systems are not accurate enough for education", "B) Dr. Liu's regulatory approach could create inequity by disadvantaging poorer schools", "C) Teachers are unwilling to adapt their teaching methods", "D) Technology companies should have more power in schools"]},
    {"number": 10, "options": ["A) Rural schools with limited budgets", "B) Well-funded schools with compliance and IT resources", "C) Schools with the least AI usage", "D) All schools equally, regardless of size or funding"]},
]

def update_questions(part, questions_list):
    print(f"\n=== Updating {part} ===")
    for item in questions_list:
        number = item['number']
        options = item['options']
        
        update_data = {
            "option_a": options[0],
            "option_b": options[1],
            "option_c": options[2],
            "option_d": options[3]
        }
        
        url = f"{supabase_url}/rest/v1/questions?section=eq.Reading&part=eq.{part}&number=eq.{number}"
        
        try:
            data = json.dumps(update_data).encode('utf-8')
            req = urllib.request.Request(url, data=data, headers=headers, method='PATCH')
            with urllib.request.urlopen(req) as response:
                print(f"✓ {part} Q{number}: Updated")
        except Exception as e:
            print(f"✗ {part} Q{number}: Error - {e}")

update_questions("R2", r2_data)
update_questions("R3", r3_data)
update_questions("R4", r4_data)

print("\n=== All done! ===")
